all: matrix_multiplication

#--------------------------------------------------------------------                                                                                         
# Makefile for matrix_multiplication.cu
matrix_multiplication: matrix_multiplication.cu
	nvcc matrix_multiplication.cu -o matrix_multiplication
run2: matrix_multiplication
	./matrix_multiplication 2 2 2
run4: matrix_multiplication
	./matrix_multiplication 4 4 4
run8: matrix_multiplication
	./matrix_multiplication 8 8 8
run16: matrix_multiplication
	./matrix_multiplication 16 16 16
run32: matrix_multiplication
	./matrix_multiplication 32 32 32
run64: matrix_multiplication
	./matrix_multiplication 64 64 64
run128: matrix_multiplication
	./matrix_multiplication 128 128 128
run256: matrix_multiplication
	./matrix_multiplication 256 256 256
run512: matrix_multiplication
	./matrix_multiplication 512 512 512
run1024: matrix_multiplication
	./matrix_multiplication 1024 1024 1024
run2048: matrix_multiplication
	./matrix_multiplication 2048 2048 2048
run4096: matrix_multiplication
	./matrix_multiplication 4096 4096 4096
run8192: matrix_multiplication
	./matrix_multiplication 8192 8192 8192
run16384: matrix_multiplication
	./matrix_multiplication 16384 16384 16384